openapi: 3.0.3
info:
  title: Railestate Users API
  version: "1.0.0"
  description: API for retrieving user profile information from Railestate.
servers:
  - url: https://railestate.herokuapp.com
    description: Production Server
paths:
  /users/profile/show:
    get:
      summary: Retrieve current user's profile
      description: Returns the profile information of the currently authenticated user.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Successful retrieval of user profile data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        "401":
          description: Unauthorized – API token missing or invalid.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >
        Provide your API token in the header using the format: 
        `Authorization: Token <your_api_token>`
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: "user@example.com"
        full_name:
          type: string
          example: "John Doe"
        avatar_url:
          type: string
          format: uri
          example: "https://example.com/avatar.png"
        provider:
          type: string
          example: "google_oauth2"
        uid:
          type: string
          example: "1234567890"
        created_at:
          type: string
          format: date-time
          example: "2025-01-01T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-02-01T12:00:00Z"
      required:
        - id
        - email
        - full_name
        - created_at
        - updated_at
