openapi: 3.0.1
info:
  title: Railestate API
  version: "1.0.0"
  description: |
    API documentation for Railestate.
    All endpoints are protected and require a valid API token for authorization.
servers:
  - url: https://railestate.herokuapp.com
paths:
  /api/v1/listings:
    get:
      summary: Retrieve all listings
      description: |
        Returns a JSON array of all listing objects.
        This endpoint is protected; include your API token in the `Authorization` header.
      tags:
        - Listings
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A list of listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
        '401':
          description: Unauthorized – API token missing or invalid.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >
        Provide your API token in the header using the format:
        `Authorization: Token <your_api_token>`
  schemas:
    Listing:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Beautiful House"
        address:
          type: string
          example: "123 Main St, Anytown, USA"
        image_url:
          type: string
          format: uri
          example: "https://s3.amazonaws.com/your-bucket/image.png"
        price:
          type: number
          format: float
          example: 350000.0
        buy_or_rent:
          type: boolean
          example: true
        description:
          type: string
          example: "A lovely three-bedroom house."
        created_at:
          type: string
          format: date-time
          example: "2025-01-01T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-02-01T12:00:00Z"
